# Generated by Django 2.1.1 on 2020-05-16 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200502_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_name',
            field=models.CharField(default='__user_name__', max_length=30),
            preserve_default=False,
        ),
    ]
