# Generated by Django 2.1.1 on 2020-06-01 18:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('datatype', '0001_initial'),
        ('community', '0002_community_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='datatype',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='datatype',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='community.Community'),
        ),
    ]
