# Generated by Django 2.1.1 on 2020-05-28 12:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datatype', '0002_auto_20200413_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datatype',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
