# Generated by Django 2.1.1 on 2020-06-01 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('property', '0001_initial'),
        ('datetimefield', '0002_datetimefield_instance'),
    ]

    operations = [
        migrations.AddField(
            model_name='datetimefield',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.Property'),
        ),
    ]
