# Generated by Django 2.1.1 on 2020-06-09 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_community_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
