# Generated by Django 2.1.1 on 2020-04-13 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=500)),
                ('generic', models.BooleanField(choices=[(0, 'Custom'), (1, 'Generic')], db_index=True)),
            ],
            options={
                'verbose_name': 'datatype',
                'verbose_name_plural': 'datatypes',
            },
        ),
    ]
