# Generated by Django 2.1.1 on 2020-05-04 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('data', models.TextField()),
            ],
            options={
                'verbose_name': 'annotation',
                'verbose_name_plural': 'annotations',
                'ordering': ['created'],
            },
        ),
    ]
