# Generated by Django 2.1.1 on 2020-04-13 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('property', '0001_initial'),
        ('integerfield', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='integerfield',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.Property'),
        ),
    ]
