# Generated by Django 2.1.1 on 2020-06-04 01:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='follow_source', to=settings.AUTH_USER_MODEL)),
                ('target', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='follow_target', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'follow',
                'verbose_name_plural': 'follows',
            },
        ),
    ]
