# Generated by Django 2.1.1 on 2020-04-13 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('type', models.SmallIntegerField(choices=[(0, 'Text'), (1, 'Number'), (2, 'Datetime'), (4, 'Video'), (5, 'Audio'), (6, 'Image'), (7, 'Email'), (8, 'URL'), (9, 'Location')])),
                ('generic', models.BooleanField(choices=[(0, 'Custom'), (1, 'Generic')], db_index=True)),
                ('required', models.BooleanField(db_index=True)),
            ],
            options={
                'verbose_name': 'property',
                'verbose_name_plural': 'properties',
            },
        ),
    ]
