# Generated by Django 2.1.1 on 2020-06-01 18:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('property', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('datatype', '0002_auto_20200601_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='property',
            name='datatype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datatype.DataType'),
        ),
    ]
