# Generated by Django 2.1.1 on 2020-05-16 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_auto_20200413_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='type',
            field=models.SmallIntegerField(choices=[(0, 'Text'), (1, 'Number'), (2, 'Datetime'), (4, 'Video'), (5, 'Audio'), (6, 'Image'), (7, 'Email'), (8, 'URL'), (9, 'Location'), (10, 'MultilineText')]),
        ),
    ]
